export const GET_RECIPE = 'GET_RECIPE';
export const GET_RECIPES = 'GET_RECIPES';
export const GET_TOP_BREAKFAST_RECIPE = 'GET_TOP_BREAKFAST_RECIPE';
export const GET_TOP_LUNCH_RECIPE = 'GET_TOP_LUNCH_RECIPE';
export const GET_TOP_DINNER_RECIPE = 'GET_TOP_DINNER_RECIPE';
